### ISSUE TITLE
readme note tweaks - low priority

### ISSUE THREAD

**Issue by johndpope** [xmartlabs/benderthon#1]
it seems that a ckpt.meta file is needed in addition to .ckpt file
<img width="1165" alt="screen shot 2017-06-07 at 1 12 34 pm" src="https://user-images.githubusercontent.com/289994/26891439-027a3a46-4b83-11e7-9698-ca7893bfc168.png">

**Comment by bryant1410** [comment]
Yeah, it needs the whole ".ckpt" files. So, if you save them in "path.ckpt", you need the "path.ckpt.meta", "path.ckpt.data-*" and "path.ckpt.index" files
