### ISSUE TITLE
enhancement - support for Bundle File / generator.proto

### ISSUE THREAD

**Issue by johndpope** [xmartlabs/benderthon#2]
https://github.com/tensorflow/magenta/tree/master/magenta/models/melody_rnn#creating-a-bundle-file

_Creating a Bundle File

The bundle format is a convenient way of combining the model checkpoint, metagraph, and some metadata about the model into a single file._

https://github.com/tensorflow/magenta/blob/master/magenta/protobuf/generator.proto

message GeneratorBundle {
  // Details about the generator that created this bundle.
  GeneratorDetails generator_details = 1;

  // Details about this specific bundle.
  message BundleDetails {
    // A short, human-readable text description of the bundle (e.g., training
    // data, hyper parameters, etc.).
    string description = 1;
  }
  BundleDetails bundle_details = 4;

  // The contents of the checkpoint file generated by the Saver.
  // This is a repeated field so we can eventually support sharded checkpoints.
  // But for now, we support only 1 file.
  **repeated bytes checkpoint_file = 2;**

  // The contents of the metagraph file generated by the Saver.
  **bytes metagraph_file = 3;**
}

I might make a tiny swift script to load generator files / then spit out the associated metagraph file.

**Comment by johndpope** [comment]
I grabbed this  .mag file http://download.magenta.tensorflow.org/models/attention_rnn.mag

and built out some swift code here to break it apart.
https://github.com/johndpope/tensorflow/blob/master/tensorflow/swift/Sources/main.swift



if there's interest in seeing code - it's possible to save this local **misc** folder location 
https://github.com/johndpope/tensorflow/tree/master/tensorflow/swift/misc



the basic gist of code
https://gist.github.com/johndpope/442426d8bda7b6cbfee908b329286f87



➜  misc git:(master) ✗ benderthon tf-freeze attention_rnn.chkpt test.pb **# prediction**
2017-06-07 15:55:07.791562: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-07 15:55:07.791589: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-06-07 15:55:07.791605: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-07 15:55:07.791610: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "/usr/local/bin/benderthon", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/benderthon/cmdline.py", line 26, in main
    tf_freeze.freeze_from_checkpoint(args.input_checkpoint, args.output_file, args.output_node_names)
  File "/usr/local/lib/python3.6/site-packages/benderthon/tf_freeze.py", line 37, in freeze_from_checkpoint
    clear_devices=True, initializer_nodes='')
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/tools/freeze_graph.py", line 116, in freeze_graph_with_def_protos
    variable_names_blacklist=variable_names_blacklist)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/graph_util_impl.py", line 204, in convert_variables_to_constants
    inference_graph = extract_sub_graph(input_graph_def, output_node_names)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/graph_util_impl.py", line 141, in extract_sub_graph
    assert d in name_to_node_map, "%s is not in graph" % d
AssertionError: **prediction** is not in graph

I tried substituting in node values but they all seem to fail. 

node: conv2d0_b
node: conv2d1_w
node: conv2d1_b
node: conv2d2_w
node: conv2d2_b
node: mixed3a_1x1_w
node: mixed3a_1x1_b
node: mixed3a_3x3_bottleneck_w
node: mixed3a_3x3_bottleneck_b
node: mixed3a_3x3_w
node: mixed3a_3x3_b
node: mixed3a_5x5_bottleneck_w
node: mixed3a_5x5_bottleneck_b
node: mixed3a_5x5_w
node: mixed3a_5x5_b
node: mixed3a_pool_reduce_w
node: mixed3a_pool_reduce_b
node: mixed3b_1x1_w
node: mixed3b_1x1_b
node: mixed3b_3x3_bottleneck_w
node: mixed3b_3x3_bottleneck_b
node: mixed3b_3x3_w
node: mixed3b_3x3_b
node: mixed3b_5x5_bottleneck_w
node: mixed3b_5x5_bottleneck_b
node: mixed3b_5x5_w
node: mixed3b_5x5_b
node: mixed3b_pool_reduce_w
node: mixed3b_pool_reduce_b
node: mixed4a_1x1_w
node: mixed4a_1x1_b
node: mixed4a_3x3_bottleneck_w
node: mixed4a_3x3_bottleneck_b
node: mixed4a_3x3_w
node: mixed4a_3x3_b
node: mixed4a_5x5_bottleneck_w
node: mixed4a_5x5_bottleneck_b
node: mixed4a_5x5_w
node: mixed4a_5x5_b
node: mixed4a_pool_reduce_w
node: mixed4a_pool_reduce_b
node: mixed4b_1x1_w
node: mixed4b_1x1_b
node: mixed4b_3x3_bottleneck_w
node: mixed4b_3x3_bottleneck_b
node: mixed4b_3x3_w
node: mixed4b_3x3_b
node: mixed4b_5x5_bottleneck_w
node: mixed4b_5x5_bottleneck_b
node: mixed4b_5x5_w
node: mixed4b_5x5_b
node: mixed4b_pool_reduce_w
node: mixed4b_pool_reduce_b
node: mixed4c_1x1_w
node: mixed4c_1x1_b
node: mixed4c_3x3_bottleneck_w
node: mixed4c_3x3_bottleneck_b
node: mixed4c_3x3_w
node: mixed4c_3x3_b
node: mixed4c_5x5_bottleneck_w
node: mixed4c_5x5_bottleneck_b
node: mixed4c_5x5_w
node: mixed4c_5x5_b
node: mixed4c_pool_reduce_w
node: mixed4c_pool_reduce_b
node: mixed4d_1x1_w
node: mixed4d_1x1_b
node: mixed4d_3x3_bottleneck_w
node: mixed4d_3x3_bottleneck_b
node: mixed4d_3x3_w
node: mixed4d_3x3_b
node: mixed4d_5x5_bottleneck_w
node: mixed4d_5x5_bottleneck_b
node: mixed4d_5x5_w
node: mixed4d_5x5_b
node: mixed4d_pool_reduce_w
node: mixed4d_pool_reduce_b
node: mixed4e_1x1_w
node: mixed4e_1x1_b
node: mixed4e_3x3_bottleneck_w
node: mixed4e_3x3_bottleneck_b
node: mixed4e_3x3_w
node: mixed4e_3x3_b
node: mixed4e_5x5_bottleneck_w
node: mixed4e_5x5_bottleneck_b
node: mixed4e_5x5_w
node: mixed4e_5x5_b
node: mixed4e_pool_reduce_w
node: mixed4e_pool_reduce_b
node: mixed5a_1x1_w
node: mixed5a_1x1_b
node: mixed5a_3x3_bottleneck_w
node: mixed5a_3x3_bottleneck_b
node: mixed5a_3x3_w
node: mixed5a_3x3_b
node: mixed5a_5x5_bottleneck_w
node: mixed5a_5x5_bottleneck_b
node: mixed5a_5x5_w
node: mixed5a_5x5_b
node: mixed5a_pool_reduce_w
node: mixed5a_pool_reduce_b
node: mixed5b_1x1_w
node: mixed5b_1x1_b
node: mixed5b_3x3_bottleneck_w
node: mixed5b_3x3_bottleneck_b
node: mixed5b_3x3_w
node: mixed5b_3x3_b
node: mixed5b_5x5_bottleneck_w
node: mixed5b_5x5_bottleneck_b
node: mixed5b_5x5_w
node: mixed5b_5x5_b
node: mixed5b_pool_reduce_w
node: mixed5b_pool_reduce_b
node: head0_bottleneck_w
node: head0_bottleneck_b
node: nn0_w
node: nn0_b
node: softmax0_w
node: softmax0_b
node: head1_bottleneck_w
node: head1_bottleneck_b
node: nn1_w
node: nn1_b
node: softmax1_w
node: softmax1_b
node: softmax2_w
node: softmax2_b
node: conv2d0_pre_relu/conv
node: conv2d0_pre_relu
node: conv2d0
node: maxpool0
node: localresponsenorm0
node: conv2d1_pre_relu/conv
node: conv2d1_pre_relu
node: conv2d1
node: conv2d2_pre_relu/conv
node: conv2d2_pre_relu
node: conv2d2
node: localresponsenorm1
node: maxpool1
node: mixed3a_1x1_pre_relu/conv
node: mixed3a_1x1_pre_relu
node: mixed3a_1x1
node: mixed3a_3x3_bottleneck_pre_relu/conv
node: mixed3a_3x3_bottleneck_pre_relu
node: mixed3a_3x3_bottleneck
node: mixed3a_3x3_pre_relu/conv
node: mixed3a_3x3_pre_relu
node: mixed3a_3x3
node: mixed3a_5x5_bottleneck_pre_relu/conv
node: mixed3a_5x5_bottleneck_pre_relu
node: mixed3a_5x5_bottleneck
node: mixed3a_5x5_pre_relu/conv
node: mixed3a_5x5_pre_relu
node: mixed3a_5x5
node: mixed3a_pool
node: mixed3a_pool_reduce_pre_relu/conv
node: mixed3a_pool_reduce_pre_relu
node: mixed3a_pool_reduce
node: mixed3a/concat_dim
node: mixed3a
node: mixed3b_1x1_pre_relu/conv
node: mixed3b_1x1_pre_relu
node: mixed3b_1x1
node: mixed3b_3x3_bottleneck_pre_relu/conv
node: mixed3b_3x3_bottleneck_pre_relu
node: mixed3b_3x3_bottleneck
node: mixed3b_3x3_pre_relu/conv
node: mixed3b_3x3_pre_relu
node: mixed3b_3x3
node: mixed3b_5x5_bottleneck_pre_relu/conv
node: mixed3b_5x5_bottleneck_pre_relu
node: mixed3b_5x5_bottleneck
node: mixed3b_5x5_pre_relu/conv
node: mixed3b_5x5_pre_relu
node: mixed3b_5x5
node: mixed3b_pool
node: mixed3b_pool_reduce_pre_relu/conv
node: mixed3b_pool_reduce_pre_relu
node: mixed3b_pool_reduce
node: mixed3b/concat_dim
node: mixed3b
node: maxpool4
node: mixed4a_1x1_pre_relu/conv
node: mixed4a_1x1_pre_relu
node: mixed4a_1x1
node: mixed4a_3x3_bottleneck_pre_relu/conv
node: mixed4a_3x3_bottleneck_pre_relu
node: mixed4a_3x3_bottleneck
node: mixed4a_3x3_pre_relu/conv
node: mixed4a_3x3_pre_relu
node: mixed4a_3x3
node: mixed4a_5x5_bottleneck_pre_relu/conv
node: mixed4a_5x5_bottleneck_pre_relu
node: mixed4a_5x5_bottleneck
node: mixed4a_5x5_pre_relu/conv
node: mixed4a_5x5_pre_relu
node: mixed4a_5x5
node: mixed4a_pool
node: mixed4a_pool_reduce_pre_relu/conv
node: mixed4a_pool_reduce_pre_relu
node: mixed4a_pool_reduce
node: mixed4a/concat_dim
node: mixed4a
node: mixed4b_1x1_pre_relu/conv
node: mixed4b_1x1_pre_relu
node: mixed4b_1x1
node: mixed4b_3x3_bottleneck_pre_relu/conv
node: mixed4b_3x3_bottleneck_pre_relu
node: mixed4b_3x3_bottleneck
node: mixed4b_3x3_pre_relu/conv
node: mixed4b_3x3_pre_relu
node: mixed4b_3x3
node: mixed4b_5x5_bottleneck_pre_relu/conv
node: mixed4b_5x5_bottleneck_pre_relu
node: mixed4b_5x5_bottleneck
node: mixed4b_5x5_pre_relu/conv
node: mixed4b_5x5_pre_relu
node: mixed4b_5x5
node: mixed4b_pool
node: mixed4b_pool_reduce_pre_relu/conv
node: mixed4b_pool_reduce_pre_relu
node: mixed4b_pool_reduce
node: mixed4b/concat_dim
node: mixed4b
node: mixed4c_1x1_pre_relu/conv
node: mixed4c_1x1_pre_relu
node: mixed4c_1x1
node: mixed4c_3x3_bottleneck_pre_relu/conv
node: mixed4c_3x3_bottleneck_pre_relu
node: mixed4c_3x3_bottleneck
node: mixed4c_3x3_pre_relu/conv
node: mixed4c_3x3_pre_relu
node: mixed4c_3x3
node: mixed4c_5x5_bottleneck_pre_relu/conv
node: mixed4c_5x5_bottleneck_pre_relu
node: mixed4c_5x5_bottleneck
node: mixed4c_5x5_pre_relu/conv
node: mixed4c_5x5_pre_relu
node: mixed4c_5x5
node: mixed4c_pool
node: mixed4c_pool_reduce_pre_relu/conv
node: mixed4c_pool_reduce_pre_relu
node: mixed4c_pool_reduce
node: mixed4c/concat_dim
node: mixed4c
node: mixed4d_1x1_pre_relu/conv
node: mixed4d_1x1_pre_relu
node: mixed4d_1x1
node: mixed4d_3x3_bottleneck_pre_relu/conv
node: mixed4d_3x3_bottleneck_pre_relu
node: mixed4d_3x3_bottleneck
node: mixed4d_3x3_pre_relu/conv
node: mixed4d_3x3_pre_relu
node: mixed4d_3x3
node: mixed4d_5x5_bottleneck_pre_relu/conv
node: mixed4d_5x5_bottleneck_pre_relu
node: mixed4d_5x5_bottleneck
node: mixed4d_5x5_pre_relu/conv
node: mixed4d_5x5_pre_relu
node: mixed4d_5x5
node: mixed4d_pool
node: mixed4d_pool_reduce_pre_relu/conv
node: mixed4d_pool_reduce_pre_relu
node: mixed4d_pool_reduce
node: mixed4d/concat_dim
node: mixed4d
node: mixed4e_1x1_pre_relu/conv
node: mixed4e_1x1_pre_relu
node: mixed4e_1x1
node: mixed4e_3x3_bottleneck_pre_relu/conv
node: mixed4e_3x3_bottleneck_pre_relu
node: mixed4e_3x3_bottleneck
node: mixed4e_3x3_pre_relu/conv
node: mixed4e_3x3_pre_relu
node: mixed4e_3x3
node: mixed4e_5x5_bottleneck_pre_relu/conv
node: mixed4e_5x5_bottleneck_pre_relu
node: mixed4e_5x5_bottleneck
node: mixed4e_5x5_pre_relu/conv
node: mixed4e_5x5_pre_relu
node: mixed4e_5x5
node: mixed4e_pool
node: mixed4e_pool_reduce_pre_relu/conv
node: mixed4e_pool_reduce_pre_relu
node: mixed4e_pool_reduce
node: mixed4e/concat_dim
node: mixed4e
node: maxpool10
node: mixed5a_1x1_pre_relu/conv
node: mixed5a_1x1_pre_relu
node: mixed5a_1x1
node: mixed5a_3x3_bottleneck_pre_relu/conv
node: mixed5a_3x3_bottleneck_pre_relu
node: mixed5a_3x3_bottleneck
node: mixed5a_3x3_pre_relu/conv
node: mixed5a_3x3_pre_relu
node: mixed5a_3x3
node: mixed5a_5x5_bottleneck_pre_relu/conv
node: mixed5a_5x5_bottleneck_pre_relu
node: mixed5a_5x5_bottleneck
node: mixed5a_5x5_pre_relu/conv
node: mixed5a_5x5_pre_relu
node: mixed5a_5x5
node: mixed5a_pool
node: mixed5a_pool_reduce_pre_relu/conv
node: mixed5a_pool_reduce_pre_relu
node: mixed5a_pool_reduce
node: mixed5a/concat_dim
node: mixed5a
node: mixed5b_1x1_pre_relu/conv
node: mixed5b_1x1_pre_relu
node: mixed5b_1x1
node: mixed5b_3x3_bottleneck_pre_relu/conv
node: mixed5b_3x3_bottleneck_pre_relu
node: mixed5b_3x3_bottleneck
node: mixed5b_3x3_pre_relu/conv
node: mixed5b_3x3_pre_relu
node: mixed5b_3x3
node: mixed5b_5x5_bottleneck_pre_relu/conv
node: mixed5b_5x5_bottleneck_pre_relu
node: mixed5b_5x5_bottleneck
node: mixed5b_5x5_pre_relu/conv
node: mixed5b_5x5_pre_relu
node: mixed5b_5x5
node: mixed5b_pool
node: mixed5b_pool_reduce_pre_relu/conv
node: mixed5b_pool_reduce_pre_relu
node: mixed5b_pool_reduce
node: mixed5b/concat_dim
node: mixed5b
node: avgpool0
node: head0_pool
node: head0_bottleneck_pre_relu/conv
node: head0_bottleneck_pre_relu
node: head0_bottleneck
node: head0_bottleneck/reshape/shape
node: head0_bottleneck/reshape
node: nn0_pre_relu/matmul
node: nn0_pre_relu
node: nn0
node: nn0/reshape/shape
node: nn0/reshape
node: softmax0_pre_activation/matmul
node: softmax0_pre_activation
node: softmax0
node: head1_pool
node: head1_bottleneck_pre_relu/conv
node: head1_bottleneck_pre_relu
node: head1_bottleneck
node: head1_bottleneck/reshape/shape
node: head1_bottleneck/reshape
node: nn1_pre_relu/matmul
node: nn1_pre_relu
node: nn1
node: nn1/reshape/shape
node: nn1/reshape
node: softmax1_pre_activation/matmul
node: softmax1_pre_activation
node: softmax1
node: avgpool0/reshape/shape
node: avgpool0/reshape
node: softmax2_pre_activation/matmul
node: softmax2_pre_activation
node: softmax2
node: output
node: output1
node: output2

**Comment by johndpope** [comment]
benderthon tf-freeze attention_rnn.chkpt output.pb **RNN/Shape**
2017-06-07 16:38:59.072818: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-07 16:38:59.072857: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-06-07 16:38:59.072867: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-07 16:38:59.072874: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Converted 0 variables to const ops.
**4 ops in the final graph.**

**Comment by bryant1410** [comment]
So, how did you generate the checkpoint file?

**Comment by johndpope** [comment]
The bundle mag file has it included. I just ripped it out in swift. The other ticket described how.

**Comment by johndpope** [comment]
This code https://github.com/johndpope/tensorflow/blob/master/tensorflow/swift/Sources/main.swift

**Comment by johndpope** [comment]
But am still in the dark around which nodes are essential ones.

**Comment by bryant1410** [comment]
> But am still in the dark around which nodes are essential ones.

There's a node there called "output", maybe that's the output

**Comment by bryant1410** [comment]
> The bundle mag file has it included. I just ripped it out in swift. The other ticket described how.

So, were you able to successfully use? But it'd be nice if it just worked with mag files, doesn't it? You can work in extending it if you want to.
