### ISSUE TITLE
enhancement - optimize_for_inference

### ISSUE THREAD

**Issue by johndpope** [xmartlabs/benderthon#3]
seems like an additional step is needed to get checkpoint / pb files in order for mobile.
I'm imaging an additional parameter to pass into benderthon to handle this.

https://github.com/hollance/TensorFlow-iOS-Example

The model is already included in the app as inference.pb. If you train the model with different settings, you need to run the freeze_graph and **optimize_for_inference** tools to create a new inference.pb.

perhaps you can cherry pick this code?
https://gist.github.com/omimo/5d393ed5b64d2ca0c591e4da04af6009#file-prep_model-py-L8

also it seems this op and node is critical to getting inference working.
restore_op_name = "save/restore_all"
filename_tensor_name = "save/Const:0"

https://github.com/icodingc/backup/blob/f867f8bdd9907e411653fa6f97d57f6982984c41/neuralstyle/freeze_graph_toy/gen_freeze_graph.py

**Comment by johndpope** [comment]
it seems the mag file / Tensorflow_MetaGraphDef includes a helpful saverDef 
from this / can ascertain 

saverDef: gRPCTensorFlow.Tensorflow_SaverDef:
filename_tensor_name: "save_1/Const:0"
save_tensor_name: "save_1/control_dependency:0"
restore_op_name: "save_1/restore_all"
max_to_keep: 5
keep_checkpoint_every_n_hours: 10000
version: V1


https://gist.github.com/johndpope/99038722132de7f1e80ad96bd7e7e21f

**Comment by johndpope** [comment]
fyi - code to rip apart bundle file. https://raw.githubusercontent.com/tensorflow/magenta/d8efb2a1984caadddd5e9290853b196dd90eba4a/magenta/scripts/unpack_bundle.py

**Comment by johndpope** [comment]
after extracting the chkpt via the above script -> 
benderthon tf-freeze attention_rnn.chkpt test.db save_1/restore_all

this dumps out 72 ops in the final graph. will try running the optimize script.

**Comment by bryant1410** [comment]
Oh, didn't know about `optimize_for_inference_lib`. It'd be nice to add it.

**Comment by johndpope** [comment]
Fyi - there's another handy bazel script to get the input output variables 

https://github.com/tensorflow/magenta/issues/715

**Comment by johndpope** [comment]
bin/tensorflow/tools/graph_transforms/summarize_graph

**Comment by johndpope** [comment]
@bryant1410 - fyi - https://github.com/tf-coreml/tf-coreml

**Comment by bryant1410** [comment]
@johndpope yeah, thanks! I read about it last night.
