### ISSUE TITLE
Suggestion to request help to port GAN / VAE tensorflow code 

### ISSUE THREAD

**Issue by johndpope** [xmartlabs/benderthon#4]
Came across this cook book for gan tensorflow 
https://github.com/wiseodd/generative-models

The snippets are small / bite sized.

Suppose we fork this / and add in code to spit out trained /frozen models that could then be imported to bender.

Seems to be enough interest  in bender that this would be a nice academic excercise for someone to contribute.

It would also help feed back into bender as test cases.

**Comment by bryant1410** [comment]
you mean like creating a repo of example generative models for bender? Maybe the frozen protobufs and iOS code for the example apps? Sounds good!

**Comment by johndpope** [comment]
fyi - https://github.com/PerfectlySoft/Perfect-TensorFlow
